buildings = [
"ACA|Academic Annex",
"ACE|Applied Computational Engineering and Sciences Building",
"ART|Art Building and Museum",
"ATT|AT&T Executive Education and Conference Center",
"BAT|Batts Hall",
"BEL|Belmont Hall",
"BEN|Benedict Hall",
"BIO|Biological Laboratories",
"BMA|Blanton Museum of Art",
"BME|Biomedical Engineering Building",
"BRB|Bernard and Audre Rapoport Building",
"BTL|Battle Hall",
"BUR|Burdine Hall",
"CAL|Calhoun Hall",
"CBA|McCombs School of Business",
"CCJ|John B. Connally Center for Justice",
"CMA|Jesse H Jones Communication Center Building A",
"CMB|Jesse H Jones Communication Center Building B",
"CPE|Chemical and Petroleum Engineering Building",
"CRD|Carothers Dormatory ",
"CSA|Computer Science Annex",
"DFA|E. William Doty Fine Arts Building",
"ECJ|Ernest Cockrell Jr. Hall",
"ENS|Engineering-Sciences Building",
"EPS|E. P. Schoch Building",
"ETC|Engineering Teaching Center II",
"FAC|Peter T. Flawn Academic Center",
"GAR|Garrison Hall",
"GEA|Mary E. Gearing Hall",
"GOL|Goldsmith Hall",
"GRG|Geography Building",
"GSB|Graduate School of Business Building",
"HMA|Hogg Memorial Auditorium",
"HRH|Homer Rainey Hall",
"HSM|William Randolph Hearst Building (formerly CMC)",
"JES|Beauford H. Jester Center",
"JGB|Jackson Geological Sciences Building (formerly GEO)",
"JON|Jesse H. Jones Hall",
"LBJ|Lyndon B. Johnson Library",
"MAI|Main Building",
"MBB|Louise and James Robert Moffet Molecular Biology Building",
"MEZ|Mezes Hall",
"MRH|Music Building East and Music Building/Recital Hall",
"NMS|Neural Molecular Science Building",
"NOA|North Office Building",
"NST|Nano Science and Technology Building",
"NUR|Nursing School",
"PAI|T.S. Painter Hall",
"PAR|Parlin Hall",
"PAT|J.T. Paterson Laboratories Building",
"PHR|Pharmacy Building",
"RAS|Russell A. Steindam Hall",
"RLM|Robert Lee Moore Hall",
"SEA|Sarah M. and Charles E. Seay Building",
"SRH|Sid Richardson Hall",
"SSW|School of Social Work Building",
"SUT|Sutton Hall",
"SZB|George I. Sanchez Building",
"TAY|T.U. Taylor Hall",
"TCC|Joe C. Thompson Conference Center",
"TNH|Townes Hall",
"UNB|Union Building",
"UTC|University Teaching Center",
"WAG|Waggoner Hall",
"WCH|Will C. Hogg Building",
"WEL|Robert A. Welch Hall",
"WMB|West Mall Office Building",
"WRW|W.R. Woolrich Laboratories",
]


for I in xrange(0,len(buildings)):
    b = buildings[I]
    (abbr,name) = b.split('|')
    print "<%d> %s %s" % (I+1,abbr,name)

print "<888> Don't know"
print "<999> Other"

